<?php

namespace Tests\Feature\Post;

use App\Models\Post;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Str;
use Tests\TestCase;

class CreatePost extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    /**
     * A user can create a BlogPost containing these fields:
        A title [Required]
        A content [Required]. It will come later from a Wysiwyg
        A Slug [Optional - can be autogenerated from the title]
        published_at date [Optional - if empty it will be publish now)
        These fields will be automatically generate:
        A reading-time information - [That will be calculated]
     */
    /**
     * @test
     */
    public function user_can_create_a_post(): void
    {
        $this->withoutExceptionHandling();
        $attributes = [
            'title' => Str::random(20),
            'content' => Str::random(250),
            'slug' => Str::random(10),
        ];
        $this->post('/posts', $attributes);
    }
}
